### ISSUE TITLE
[BUG] Don't get the comment with preview url on PR merged

### ISSUE THREAD

**Issue by masterbd** [FirebaseExtended/action-hosting-deploy#111]
### Action config

```
on:
  push:
    branches: [master]
    ...
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: ***
        expires: 14d
        channelID: preview
```

### Error message

N/A

### Expected behavior

To post the comment with preview url.

### Actual behavior

I don't get any comment with preview url for PR merged configuration.
