### ISSUE TITLE
[BUG] Error: Input required and not supplied: firebaseServiceAccount

### ISSUE THREAD

**Issue by ws333** [FirebaseExtended/action-hosting-deploy#134]
We get `Error: Input required and not supplied: firebaseServiceAccount` whenever the workflow is triggered.

No error when we rerun the job manually.

Repo: http://github.com/bjerkio/website

### Action config

```
  - name: Upload website
    uses: FirebaseExtended/action-hosting-deploy@v0
    id: firebase
    with:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BJERK_IO }}'
      projectId: bjerk-io
    env:
      FIREBASE_CLI_PREVIEWS: hostingchannels
```

### Error message

```
Error: Input required and not supplied: firebaseServiceAccount
    at Object.r.getInput (/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:3939)
    at Object.<anonymous> (/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:297680)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```
