### ISSUE TITLE
Only one preview comments is generated for multisite

### ISSUE THREAD

**Issue by nwaughachukwuma** [FirebaseExtended/action-hosting-deploy#143]
With 2 workflow.yml files, each one meant to deploy to a hosting channel for a site on a firebase project, only one comment post with deploy preview url is possible on the pull_request. Also, the preview url of the workflow that finishes last overwrites that posted by the first one. 

```yaml
# workflow 1
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      projectId: '${{ secrets.PROJECT_ID }}'
      channelId: '${{ gitHub.sha }}-c1'
      target: TARGET_NAME_1
```

```yaml
# workflow 2
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      projectId: '${{ secrets.PROJECT_ID }}'
      channelId: '${{ gitHub.sha }}-c2'
      target: TARGET_NAME_2
```
