### ISSUE TITLE
[BUG] Preview deploy returns error with firebase-tools

### ISSUE THREAD

**Issue by MasaGon** [FirebaseExtended/action-hosting-deploy#158]
### Action config

```
      - name: <Development> Deploy for Preview
        if: endsWith(github.base_ref, 'release/development')
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DY_DEVELOPMENT }}'
          projectId: dy-development
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

### Error message

```
Deploying to Firebase preview channel pr911-develop
  /usr/local/bin/npx firebase-tools hosting:channel:deploy pr911-develop --expires 7d --project dy-development --json
  ***
    "status": "error",
    "error": "HTTP Error: 400, Request contains an invalid argument."
  ***
  ***
    "status": "error",
    "error": "HTTP Error: 400, Request contains an invalid argument."
  ***
  
  The process '/usr/local/bin/npx' failed with exit code 1
  Retrying deploy with the --debug flag for better error output
```

### Expected behavior

No error as a few weeks before.

### Actual behavior

With error.
