### ISSUE TITLE
[BUG] Failing to deploy on preview due to extra dash in target `channelId`

### ISSUE THREAD

**Issue by jaygcoder2020** [FirebaseExtended/action-hosting-deploy#159]
### Action config
```
- uses: FirebaseExtended/action-hosting-deploy@v0
   with:
     repoToken: '${{ secrets.GITHUB_TOKEN }}'
     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRJCT_ME }}'
     projectId: prjct-me
```

### Error message
```
/opt/hostedtoolcache/node/12.22.6/x64/bin/npx firebase-tools hosting:channel:deploy pr7-feature_react-route- --expires 7d --project prjct-me --json
  ***
    "status": "error",
    "error": "HTTP Error: 400, Request contains an invalid argument."
  ***
  ***
    "status": "error",
    "error": "HTTP Error: 400, Request contains an invalid argument."
  ***
```
### Expected behavior

Action continues to deploy the hosting app on preview

### Actual behavior

Action failed to run due to an invalid argument. It seems that the error is on the parameter after `deploy` (i.e., `pr7-feature_react-route-`. For reference, the PR branch I'm working on is `feature/react-route-pages`, so it left out the `pages` bit. I'm fine with any name, but some truncation might be needed to remove extra dashes.

*EDIT:* Just saw that there's a `channelId` field but I think this is still worth checking for autogenerated IDs.
