### ISSUE TITLE
Authenticate with workload federation credential file instead of service account key

### ISSUE THREAD

**Issue by steveoh** [FirebaseExtended/action-hosting-deploy#174]
### The use case you're trying to solve

I would like to use a federated credential file from the auth action to setup the deploy

### Change to the action that would solve that use case

```yaml
- id: auth
   name: Authenticate to Google Cloud
   uses: google-github-actions/auth@v0.3.1
   with:
       create_credentials_file: true
       workload_identity_provider: ...
       service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  - name: 🚀 Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          credentials_file_path: ${{ steps.auth.output.credentials_file_path }}
          projectId: '${{ secrets.PROJECT_ID }}'
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels 
```

**Comment by rockwotj** [comment]
Here's [more info on keyless auth in Github Actions](https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions)

FYI this is blocked on upgrading the google-auth-client library in the Firebase CLI, it's using 6.x.x which doesn't support authenticating this way. See this release: https://github.com/googleapis/google-auth-library-nodejs/releases/tag/v7.0.0

**Comment by enchorb** [comment]
Looking forward to having this merged, currently the only part of our CI/CD pipeline that doesn't work with WLIF

**Comment by rockwotj** [comment]
FWIW I have confirmed version 10.1.0 of the cli works with this auth method

**Comment by steveoh** [comment]
This may end up being relevant

https://github.com/firebase/firebase-tools/issues/3926#issuecomment-1014591105

**Comment by rockwotj** [comment]
Based on the usage of npx, this should already use the new CLI. 

https://github.com/FirebaseExtended/action-hosting-deploy/blob/ff6e7dde58a4f7f1db590927596bf683250c6cc8/src/deploy.ts#L79

I think @steveoh you just need to add the right scopes and your snippet in the issue should work.

**Comment by rockwotj** [comment]
It seems this action requires the service account is a JSON blob that it writes to disk and then overrides the environment variable that the CLI uses for auth. If you really want to use this action you'll have to hack around by reading the file output in the auth command into that input.

To be perfectly honest, it's probably simpler to just run `npx firebase-tools` in a bash script in your action. Here my redacted full action to deploy a preview branch for PR, and adds the deployed URL to an environment named "preview". You also have to add a specific label to the PR to enable this action. Hopefully this is helpful

```
name: "Frontend Preview"
on: ["pull_request"]
jobs:
  preview_frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    environment:
      name: preview
      url: ${{ steps.deployment_url.outputs.url }}
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: 'write'
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.4.4'
      with:
        token_format: 'access_token'
        access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase'
        workload_identity_provider: 'projects/redacted/locations/global/workloadIdentityPools/redacted/providers/redacted'
        service_account: 'redacted@redacted.iam.gserviceaccount.com'
        create_credentials_file: true
    - uses: ./.github/actions/setup
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Deploy
      run: npm ci && npx firebase-tools --project redacted hosting:channel:deploy ${{github.event.number}}
    - id: deployment_url
      name: Set Environment
      run: |
        URL="$(npx firebase-tools --json --project redacted --non-interactive hosting:channel:open ${{github.event.number}} | jq -r '.result.url')"
        echo "::set-output name=url::$URL"
```

**Comment by steveoh** [comment]
Ok, but this issue is for making this action work with identity federation, not dropping into the cli and doing it manually.

**Comment by rockwotj** [comment]
Sure - if you want to this action it will need to be modified to make the `firebaseServiceAccount` optional and not override the environment variable in that case.

**Comment by steveoh** [comment]
Do we have the attention of any project maintainers?

**Comment by Hallerf** [comment]
- id: auth
   name: Authenticate to Google Cloud
   uses: google-github-actions/auth@v0.3.1
   with:
       create_credentials_file: true
       workload_identity_provider: ...
       service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  - name: 🚀 Firebase Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          credentials_file_path: ${{ steps.auth.output.credentials_file_path }}
          projectId: '${{ secrets.PROJECT_ID }}'
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels 
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAWVITE_DEV }}"
          expires: 20d
          projectId: lawvitedependabot/npm_and_yarn/babel/preset-env-7.16.11package-lock.json

**Comment by steveoh** [comment]
@Hallerf that works?

**Comment by zakariazuck** [comment]
Hi! I was stuck in this problem. IDK if this concerns you: 
Issue : I manually created the firebaseServiceAccount token using `$ firebase login:ci` and save it in github actions secrets and it didn't work. 
solution : I ran `$ firebase init hosting:github` and in one of the steps it uploded a new token to github actions secrets.

**Comment by rasendubi** [comment]
You can use the following snippet to use `google-github-actions/auth`-generated credential file with `action-hosting-deploy`:
```yaml
- id: auth
  uses: 'google-github-actions/auth@v1'
  with:
    workload_identity_provider: ...
    service_account: ...
    create_credentials_file: true

- run: |
    echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    firebaseServiceAccount: "${{ env.SERVICE_ACCOUNT_KEY }}"

```

**Comment by christoph-fecra** [comment]
> You can use the following snippet to use `google-github-actions/auth`-generated credential file with `action-hosting-deploy`:
> 
> ```yaml
> - id: auth
>   uses: 'google-github-actions/auth@v1'
>   with:
>     workload_identity_provider: ...
>     service_account: ...
>     create_credentials_file: true
> 
> - run: |
>     echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV
> 
> - uses: FirebaseExtended/action-hosting-deploy@v0
>   with:
>     firebaseServiceAccount: "${{ env.SERVICE_ACCOUNT_KEY }}"
> ```

Hmm. This does NOT work for me actually. I get the error

> No OAuth tokens found

beside

> Firebase Hosting API has not been used in project *** before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebasehosting.googleapis.com/overview?project=*** then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by micksatana** [comment]
```
- uses: 'google-github-actions/auth@v2'
  id: auth
  with:
    project_id: ********
    workload_identity_provider: ********
    service_account: ********
    create_credentials_file: true
- run: |
    echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV
- name: Deploy a preview
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: ${{ secrets.GITHUB_TOKEN }}
    firebaseServiceAccount: ${{ env.SERVICE_ACCOUNT_KEY }}
    projectId: 'redacted'
    channelId: preview
```

This doesn't work for me (using `auth@v2`). It'll return error

```
Error: Failed to authenticate, have you run firebase login?
  [2025-04-24T12:13:[53](https://github.com/********/********/actions/runs/********fv/job/********#step:11:56).231Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
  [2025-04-24T12:13:53.478Z] Error: Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).
      at Gaxios._request (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/gaxios/build/src/gaxios.js:142:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async IdentityPoolClient.getImpersonatedAccessToken (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/google-auth-library/build/src/auth/baseexternalclient.js:364:26)
      at async IdentityPoolClient._BaseExternalAccountClient_internalRefreshAccessTokenAsync (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/google-auth-library/build/src/auth/baseexternalclient.js:437:34)
      at async IdentityPoolClient.refreshAccessTokenAsync (/home/runner/.npm/_npx/ba4f19[59](https://github.com/********/********/actions/runs/********/job/********#step:11:62)e38407b5/node_modules/google-auth-library/build/src/auth/baseexternalclient.js:316:20)
      at async IdentityPoolClient.getAccessToken (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/google-auth-library/build/src/auth/baseexternalclient.js:190:13)
      at async GoogleAuth.getAccessToken (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/google-auth-library/build/src/auth/googleauth.js:723:17)
      at async autoAuth (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/requireAuth.js:26:19)
      at async requireAuth (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/requireAuth.js:81:20)
      at async Object.requirePermissions [as fn] (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/requirePermissions.js:17:5)
```

**Comment by micksatana** [comment]
> Hi!
> 
> I was stuck in this problem. IDK if this concerns you: ⛔ Issue : I manually created the firebaseServiceAccount token using `$ firebase login:ci` and save it in github actions secrets and it didn't work. ✅ Solution : I ran `$ firebase init hosting:github` and in one of the steps it did automatically upload a new token to github actions secrets. And now it's working fine.
> 
> Cheers

Executing `init hosting:github` doesn't solve this issue, it will create a service account with a key which does not comply with CIS Google Cloud Platform Foundation standard. This issue is to use Workload Federation Credential file, not Service Account key.

**Comment by micksatana** [comment]
In case any one want to deploy with out using service account key, you can do without action-hosting-deploy,
just setup using google-github-actions/auth@v3 like this,

```
 steps:
   - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        project_id: simplework-day
        workload_identity_provider: projects/***/locations/global/workloadIdentityPools/***/providers/***
        service_account: ***@***.iam.gserviceaccount.com
        token_format: access_token
        access_token_scopes: |
          email
          openid
          https://www.googleapis.com/auth/cloudplatformprojects.readonly
          https://www.googleapis.com/auth/cloud-platform
          https://www.googleapis.com/auth/firebase
        export_environment_variables: true
        create_credentials_file: true
```

and just use firebase-tools directly either install in package.json or globally.

**Comment by memoricab** [comment]
The main issue is to avoid using service account keys, since also it's recommended by Google to not use service account keys since they are static and not safe to be transported and kept in other file systems. This Github action does not provide auth with Workload Identity Federation. I'm also stuck how to do this without service account key.

**Comment by AnuroopSuresh** [comment]
Full working yml for static site hosting in angular for anyone stuck. Till FirebaseExtended/action-hosting-deploy@v0 supports this natively,  hope this helps. 

Explanation:
GCP_PROJECT_NUMBER  -> your project number 
GCP_PROJECT_ID  -> your GCP project ID
GCP_SA_EMAIL -> service account email
YOUR_GITHUB_USERNAME/YOUR_REPO_NAME -> replace this as per your repo name

make sure all the necessary variables are in actions variables and secrets

Prerequisites, Create WIF in your GCP project, skip steps as necessary.
## Step 1: Create the Workload Identity Pool & Provider
```
## Step 1: Create the Workload Identity Pool & Provider
# Set your project ID
export PROJECT_ID="your-project-id"

# 1. Create the Pool
gcloud iam workload-identity-pools create "github-pool" \
    --project="${PROJECT_ID}" \
    --location="global" \
    --display-name="GitHub Actions Pool"

# 2. Create the Provider (Replace repo with "username/repo-name")
gcloud iam workload-identity-pools providers create-oidc "github-provider" \
    --project="${PROJECT_ID}" \
    --location="global" \
    --workload-identity-pool="github-pool" \
    --issuer-uri="https://token.actions.githubusercontent.com" \
    --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" \
    --attribute-condition="assertion.repository == 'YOUR_GITHUB_USERNAME/YOUR_REPO_NAME'"
 
```
## Step 2: Create & Authorize the Service Account

```
# 1. Create the Service Account
gcloud iam service-accounts create "firebase-deployer" \
    --project="${PROJECT_ID}" \
    --display-name="Firebase Deployment SA"

# 2. Grant Firebase Hosting permissions
gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:firebase-deployer@${PROJECT_ID}.iam.gserviceaccount.com" \
    --role="roles/firebasehosting.admin"

# 3. Allow GitHub to impersonate this Service Account
# Note: Use your PROJECT_NUMBER (not project ID) here
export PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format="value(projectNumber)")

gcloud iam service-accounts add-iam-policy-binding "firebase-deployer@${PROJECT_ID}.iam.gserviceaccount.com" \
    --project="${PROJECT_ID}" \
    --role="roles/iam.workloadIdentityUser" \
    --member="principalSet://iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/github-pool/attribute.repository/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME"
```

``` 
name: Deploy Angular to Firebase Hosting

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write # Required for requesting the JWT from GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install & Build
        run: |
          npm i
          npm run build --configuration=production

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{VARS.GCP_SA_EMAIL}}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Install Firebase CLI
        run: npm install -g firebase-tools


      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ${{ secrets.GCP_PROJECT_ID }} --non-interactive

```
