### ISSUE TITLE
[BUG] npm warn exec to firebase-tools package

### ISSUE THREAD

**Issue by ozeas** [FirebaseExtended/action-hosting-deploy#177]
### Action config

```yml
- uses: FirebaseExtended/action-hosting-deploy@v0
    with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_xxxxxx }}'
          channelId: my-project
          projectId: xxxxx
```

### Error message

```shell
npm WARN exec The following package was not found and will be installed: firebase-tools
  npm ERR! code E404
  npm ERR! 404 Not Found - GET https://npm.pkg.github.com/<user>/term-size/-/term-size-2.2.1.tgz
  npm ERR! 404 
  npm ERR! 404  'term-size@https://npm.pkg.github.com/<user>/term-size/-/term-size-2.2.1.tgz' is not in this registry.
  npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
  npm ERR! 404 
  npm ERR! 404 Note that you can also install from a
  npm ERR! 404 tarball, folder, http url, or git url.
```

### Actual behavior

after validated credentials, this error break proccess.
