### ISSUE TITLE
[BUG] Firebase CLI v10.0.1 is incompatible with Node.js v10.24.1

### ISSUE THREAD

**Issue by christianloosli** [FirebaseExtended/action-hosting-deploy#184]
### Action config

```
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}'
          projectId: my-awesome-project
          channelID: live
          target: ${{ env.TARGET }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

-->

### Error message

Firebase CLI v10.0.1 is incompatible with Node.js v10.24.1 Please upgrade Node.js to version >= 12
The process '/opt/hostedtoolcache/node/10.24.1/x64/bin/npx' failed with exit code 1
Retrying deploy with the --debug flag for better error output

### Expected behavior

Last deployment on December 15 still worked, no packages were updated.

### Actual behavior

We are still using AngularJs and Angular as a hybrid app. We are currently working on the full migration but it will take a while. However, we urgently need to be able to deploy again.
