### ISSUE TITLE
[BUG] Authentication on PR

### ISSUE THREAD

**Issue by MitanshuShaBa** [FirebaseExtended/action-hosting-deploy#185]
### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_XYZ }}"
    projectId: xyz
    channelId: "pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}"
    expires: 3d
```

### Error message

```
FirebaseError: Firebase: Error (auth/popup-closed-by-user).
    at Be (assert.ts:122:13)
    at Ue (assert.ts:83:29)
    at popup.ts:284:13
```

### Expected behavior

The preview website should be able to authenticate without any issues

### Actual behavior

The preview website is not allowed to authenticate the users. I use a workaround where I add the preview URL in trusted domains while testing and then remove it after I am done.
