### ISSUE TITLE
[BUG] Github Action Logs Look Corrupted

### ISSUE THREAD

**Issue by Aedalus** [FirebaseExtended/action-hosting-deploy#188]
### Action config

Created a brand new Github workflow via the firebase CLI. No modifications were made to the workflow, and the firebase project has worked fine before setting up CI/CD.

```
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_PROJECT}}'
          channelId: live
          projectId: <my-project>
```

### Error message

During the deploy step, logs look like some form of encoding/coloring got messed up. Logs also increased to over 750MB total, slowing the github UI to a crawl. [This recent issue](https://github.com/FirebaseExtended/action-hosting-deploy/issues/187) seems to point towards recent issues with a 'Faker' package being the cause, but it's not clear to me if that is the case. Would prefer if we could leave a bug report open to help track the issue, and allow others to find some information if seeing similar problems.

![image](https://user-images.githubusercontent.com/8687209/148704746-63f91393-71ef-4da6-974c-fd3d2868224a.png)
