### ISSUE TITLE
[BUG] API key missing or invalid

### ISSUE THREAD

**Issue by sanealytics** [FirebaseExtended/action-hosting-deploy#193]
### Action config

```
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAWVITE_DEV }}"
          expires: 20d
          projectId: lawvite
```
I could not using `firebase init hosting:github`. Possibly because its a private repo.
I have the repository secret for the specific action, as per [this](https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md).

I also added a Debug step to echo it to be sure. It is the JSON that I had created for the service account.

However, the deployed website tells me that the api key is invalid.

### Error message

```
{code: 'auth/invalid-api-key', message: 'Your API key is invalid, please check you have copied it correctly.', a: null}
```

### Expected behavior

Deployed site works.

### Actual behavior

Does not load.
