### ISSUE TITLE
[BUG] Permission 'cloudfunctions.functions.list' denied

### ISSUE THREAD

**Issue by teebu** [FirebaseExtended/action-hosting-deploy#203]
### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    expires: 30d
    projectId: my-awesome-project
```

### Error message

This has been working for years, and now we're starting noticing this error:

`"HTTP Error: 403, Permission 'cloudfunctions.functions.list' denied on 'projects/<my-project>/locations/-/functions'"`

### Expected behavior

Deploy without needed permission.

### Actual behavior

Fails to deploy.
