### ISSUE TITLE
[BUG] no deploy

### ISSUE THREAD

**Issue by mtenorio-cmp** [FirebaseExtended/action-hosting-deploy#205]
### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    expires: 30d
    projectId: my-awesome-project
```

### Error message

![image](https://user-images.githubusercontent.com/73306989/169316422-a0402194-231c-4824-b444-b387ff78f2d9.png)

### Expected behavior

after the build, it does not deploy the anfular project

### Actual behavior

It stays in that state for a long time, I waited for two hours, I had to cancel the deploy and publish manually. No specific error appears, you can see the attached image.
