### ISSUE TITLE
[BUG] Action not getting token

### ISSUE THREAD

**Issue by sdcaulley** [FirebaseExtended/action-hosting-deploy#214]
### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.FIREBASE_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    projectId: my-awesome-project
```

-->

### Error message

Run FirebaseExtended/action-hosting-deploy@v0
(node:1636) UnhandledPromiseRejectionWarning: HttpError: token ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
*** is not a legal HTTP header value
    at /home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:29443
(node:1636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected behavior

To get the token an deploy to Firebase Hosting

### Actual behavior

Action exiting on error.
