### ISSUE TITLE
[BUG] Firebase deploy is using public folder instead of the specified in firebase.json (build)

### ISSUE THREAD

**Issue by terry-afk** [FirebaseExtended/action-hosting-deploy#216]
### Action config

```
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
    paths:
      - src/

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRESHEN_BC365 }}'
          channelId: live
          projectId: freshen-bc365
```

```
{
  "hosting": {
    "site": "freshen-vitrine",
    "public": "build",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

### Expected behavior

I would like to deploy the build folder as specified in my firebase.json

### Actual behavior

It's actually deploying the public folder
