### ISSUE TITLE
Is it possible to enable support for web frameworks?

### ISSUE THREAD

**Issue by chinesehemp** [FirebaseExtended/action-hosting-deploy#239]
### The use case you're trying to solve

I'm trying to use GitHub actions to deploy my nextjs SSR app to firebase hosting. I understand in order to deploy a SSR app, I need to enable webframeworks with `firebase experiments:enable webframeworks` command.

### Change to the action that would solve that use case

Is this possible by adding a run: after uses: in the yml file?

```
- uses: FirebaseExtended/action-hosting-deploy@v0
        run: firebase experiments:enable webframeworks
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THECANNABISAPP_V2_DEV }}"
          channelId: live
```
