### ISSUE TITLE
[BUG] Service account creation doc incomplete

### ISSUE THREAD

**Issue by kribor** [FirebaseExtended/action-hosting-deploy#240]
### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    expires: 30d
    projectId: my-awesome-project
```

### Error message

Relevant part of deployment error: 
`Error: HTTP Error: 403, Permission 'cloudfunctions.functions.list' denied on 'projects/natural-cycles/locations/-/functions'`

### Expected behavior

Successful deployment

### Actual behavior

Failed deployment

### Proposed solution

Add another role to documentation: https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/docs/service-account.md that includes `cloudfunctions.functions.list`. Adding `Firebase Develop Admin` works but may not be "minimal required"
