### ISSUE TITLE
[BUG] Successful action reporting as failed due to GitHub 'set-output' deprecation warning

### ISSUE THREAD

**Issue by moealien** [FirebaseExtended/action-hosting-deploy#247]
### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    expires: 30d
    projectId: any-project-id
```

### Error message

Warning in run output

![2022-10-13_23 04 16](https://user-images.githubusercontent.com/57813805/195720410-36de63a3-fb2a-45f7-9452-eb3a1c2fc1ab.png)

Action is shown as failed despite deployment succeeding

![2022-10-13_23 14 11](https://user-images.githubusercontent.com/57813805/195720861-f1a795e2-9eab-415e-8c52-fb26d2a2ce48.png)

### Expected behavior

Action runs and deploys normally.

### Actual behavior

Action runs normally. GitHub deprecation warning causes the action to appear to have failed, despite the deployment working as intended, and changes being reflected on the deploy target.

### More info

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
