### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hippee-lee** [FirebaseExtended/action-hosting-deploy#250]
### Action config

Auto generated yml from: `firebase init hosting:github`

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'y'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.SHHHHH }}'
          channelId: live
          projectId: project-id
```

### Error message

When the workflow goes to run the action it doesn't find the `y` command. I am not sure if I need to also install the firebase cli tools? 
```
Run y
  y
  shell: /usr/bin/bash -e ***0***
/home/runner/work/_temp/df3c89c9-cefe-43a3-b9ce-643e31c0c6a[2](https://github.com/myrepo/private-site/actions/runs/3355971435/jobs/5560659976#step:3:2).sh: line 1: y: command not found
Error: Process completed with exit code 127.
```

### Expected behavior

I expected the action to run and have everything it needs to run included when it is installed in the github container. 

### Actual behavior

The action fails and the site is not deployed.
