### ISSUE TITLE
[BUG] Fails to deploy NextJS app

### ISSUE THREAD

**Issue by Barefoot-Dev** [FirebaseExtended/action-hosting-deploy#254]
I'm able to deploy my NextJS app directly (`firebase deploy`), however when I deploy via a PR or Merge action I get an error.

My repo is structured like so (the next app is in /frontend)
- firebase.json
- .github/workflows/firebase-hosting-merge.yml
- frontend/pages
- functions

My firebase.json is:
```
{
  "functions": {
    "source": "functions"
  },
  "hosting": {
    "source": "frontend",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"]
  }
}
```

### Action config

```
name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SDXCRYPTO_ALGOVERA }}'
          projectId: sdxcrypto-algovera
=
```

### Error message

 Error: Cannot deploy a web framework to hosting because the experiment webframeworks is not enabled. To enable webframeworks run firebase experiments:enable webframeworks
  
The process '/usr/local/bin/npx' failed with exit code 1

### Expected behavior

Deploys sucessfully.
I have enabled the webframeworks experiment and re-tried but to no avail.

### Actual behavior

Fails to deploy.

**Comment by BolajiAyodeji** [comment]
I'm experiencing the same issue. I tried adding the installation command for firebase to the action and manually enabling experiment webframeworks but it all still fails. Is there something that can be done to automatically enable this with actions?

<img width="885" alt="Screenshot 2022-11-11 at 8 07 35 AM" src="https://user-images.githubusercontent.com/30334776/201284840-37f81254-1166-483e-b9ba-d212577d3765.png">

**Comment by bruceharrison1984** [comment]
You have to enable the experiments for firebase tools as a separate command:
```yaml
      - name: Enable Firebase Experiments
        run: /usr/local/bin/npx firebase-tools@latest experiments:enable webframeworks

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POETZ_LAKE_HOUSE }}'
          channelId: live
          projectId: poetz-lake-house
```

**Comment by irealva** [comment]
Seemingly still an issue to deploy to a `preview` channel. Is there any workaround or would this get fixed anytime soon?

<img width="828" alt="Screen Shot 2022-11-17 at 4 33 28 PM" src="https://user-images.githubusercontent.com/8978670/202589445-33fe75a6-966f-4e7b-91d2-80fc3cbd9261.png">

Thanks

**Comment by Barefoot-Dev** [comment]
> You have to enable the experiments for firebase tools as a separate command:
> 
> ```yaml
>       - name: Enable Firebase Experiments
>         run: /usr/local/bin/npx firebase-tools@latest experiments:enable webframeworks
> 
>       - uses: FirebaseExtended/action-hosting-deploy@v0
>         with:
>           repoToken: '${{ secrets.GITHUB_TOKEN }}'
>           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POETZ_LAKE_HOUSE }}'
>           channelId: live
>           projectId: poetz-lake-house
> ```
> 
> It's annoying, but required for now

Should this be in a new .yml file in .github/workflows?

**Comment by Barefoot-Dev** [comment]
> You have to enable the experiments for firebase tools as a separate command:
> 
> ```yaml
>       - name: Enable Firebase Experiments
>         run: /usr/local/bin/npx firebase-tools@latest experiments:enable webframeworks
> 
>       - uses: FirebaseExtended/action-hosting-deploy@v0
>         with:
>           repoToken: '${{ secrets.GITHUB_TOKEN }}'
>           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POETZ_LAKE_HOUSE }}'
>           channelId: live
>           projectId: poetz-lake-house
> ```
> 
> It's annoying, but required for now

For me this raises the error `Could not determine the web framework in use.`

**Comment by isheraz** [comment]
I see there are 2 potential fixes submitted but @FirebaseExtended hasn't accepted either one. 
[Fix # 1](https://github.com/FirebaseExtended/action-hosting-deploy/pull/190/files)
[Fix # 2](https://github.com/FirebaseExtended/action-hosting-deploy/pull/230)

**Comment by dannydeut** [comment]
I got this to work by adding the environment variable `FIREBASE_CLI_EXPERIMENTS`.
```
- name: Deploy to Firebase
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: '${{ secrets.GITHUB_TOKEN }}'
    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
    channelId: live
    projectId: ...
  env:
  FIREBASE_CLI_EXPERIMENTS: webframeworks
 ```
