### ISSUE TITLE
[BUG] warnings for deprecated dependencies

### ISSUE THREAD

**Issue by emilbonnek** [FirebaseExtended/action-hosting-deploy#264]
### Action config
```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYAPP }}"
    projectId: myapp
```

### Error message

Getting warnings for deprecated dependencies.
```
npm WARN exec The following package was not found and will be installed: firebase-tools@11.22.0
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```

### Expected behavior
No deprecation warnings.

### Actual behavior
Several deprecation warnings.
