### ISSUE TITLE
Possibility to Deploy SSR (Next.js) app with github action

### ISSUE THREAD

**Issue by alekseykarpenko** [FirebaseExtended/action-hosting-deploy#265]
### The use case you're trying to solve

I have my GitHub action config generated alongside with setting up webframeworks support
 for SSR app (Next.js). When I deploy the app manually it all works as expected, but when using FirebaseExtended/action-hosting-deploy it leads to getting 404 for all dynamic pages (while static content works fine)ю

A quick search on this topic showed up that this GitHub action doesn't yet support deploying of Cloud Functions, that's why all the dynamic part of the app is being constantly lost while deployment. But since everything is being deployed correctly, seems Previews already support dynamic content through Cloud Functions.

### Change to the action that would solve that use case

There is potential fix for this in opened PRs:
https://github.com/FirebaseExtended/action-hosting-deploy/pull/190

**Comment by steebchen** [comment]
This would be so great to have!

**Comment by dannydeut** [comment]
I got this to work by adding the environment variable `FIREBASE_CLI_EXPERIMENTS`.
```
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ...
        env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks
 ```
