### ISSUE TITLE
[BUG] Favicon not showing after deploying

### ISSUE THREAD

**Issue by nicklbaert** [FirebaseExtended/action-hosting-deploy#267]
### Action config

```
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      - name: Build & export the NextJS app & copy it into config/hosting
        working-directory: apps/app
        run: |
          npm run build
          npm run export
          cp -R out ../../config/hosting

      - name: Deploy Preview to Firebase Hosting
        id: deploy-preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secret }}'
          expires: 5d
          projectId: <project_id>
          entryPoint: ${{ env.WORKING_DIRECTORY }}
```

### Expected behavior

We have a NextJS app with a favicon.ico inside it's public/ directory. When deploying manually using firebase deploy, the favicon shows in the browser as expected. This should also be the case when using this action.

### Actual behavior

The preview website after deploying with the above workflow **does not have a favicon**. 

In more detail: The favicon is simply empty. A get request to the favicon's route runs successfully but returns an empty image. This is the response in Postman:

<img width="179" alt="Screenshot 2023-02-27 at 08 48 02" src="https://user-images.githubusercontent.com/33283708/221504346-8905ef16-316f-4db5-9b7a-d6c15cd24bd8.png">

Any help is appreciated.
