### ISSUE TITLE
[BUG] Error (auth/invalid-api-key) on hosting PR

### ISSUE THREAD

**Issue by sophiiae** [FirebaseExtended/action-hosting-deploy#271]
### Action config

firebase-hosting-pull-request.yml
```
name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEED_CODE }}'
          projectId: need-code
```

### Error message

<img width="772" alt="Screenshot 2023-03-21 at 9 39 12 AM" src="https://user-images.githubusercontent.com/18622886/226679935-7af5e6db-8fae-4f8f-bbcf-9ea58186b884.png">

### Expected behavior

The auto PR preview link should be deployed without an error
<img width="928" alt="Screenshot 2023-03-21 at 9 41 20 AM" src="https://user-images.githubusercontent.com/18622886/226680534-5c48fe0c-6a5a-4cdd-93d5-e057c9cdc38b.png">

Link: https://need-code--pr12-update-firebase-depl-7pxhj1zl.web.app/
