### ISSUE TITLE
[Preview Channels Deployments Fails with GitHub Actions] 

### ISSUE THREAD

**Issue by Safnaj** [FirebaseExtended/action-hosting-deploy#276]
### Action config

```
name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOSSASIA_2023_DEMO }}"
          projectId: fossasia-2023-demo

```

### Error message
```
Run FirebaseExtended/action-hosting-deploy@v0
/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:3759
                const error = new RequestError(message, status, ***
                              ^

RequestError [HttpError]: Resource not accessible by integration
```
### Expected behavior

Deployments to the Preview Channels should be successful. Another workflow with live channel is working on: push events.

### Actual behavior

Deployments Fails
