### ISSUE TITLE
[BUG] The process '/usr/local/bin/npx' failed with exit code 1

### ISSUE THREAD

**Issue by yamankatby** [FirebaseExtended/action-hosting-deploy#277]
I'm getting this error in the `Deploying to production site` group

### Action config

```yaml
"on":
  push:
    branches:
      - yaman/workflow

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile && yarn run build-storybook
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount:
            "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROWY_TESTING }}"
          projectId: rowy-testing
          channelId: live
          target: rowybook

```

### Error message

```
  The process '/usr/local/bin/npx' failed with exit code 1
  Error: The process '/usr/local/bin/npx' failed with exit code 1
  ***
    conclusion: 'failure',
    output: ***
      title: 'Deploy preview failed',
      summary: "Error: The process '/usr/local/bin/npx' failed with exit code 1"
    ***
  ***
```

**Comment by MixMasterT** [comment]
I have been getting this same error.

It looks like the culprit may be that the called action () doesn't enable webframeworks.

```
Error: Cannot deploy a web framework to hosting because the experiment webframeworks is not enabled. To enable webframeworks run firebase experiments:enable webframeworks
```

**Comment by MixMasterT** [comment]
It looks like this works: 
add 
```yaml
  steps:
    - uses: FirebaseExtended/action-hosting-deploy@v0
       with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_... }'
          ...
       env:
         FIREBASE_CLI_EXPERIMENTS: webframeworks
```
The last part, adding env with FIREBASE_CLI_EXPERIMENTS is what got me past this error.

[Here](https://stackoverflow.com/questions/74426925/how-can-run-firebase-experimentsenable-webframeworks-with-github-actions) is a helpful Stack Overflow link.
