### ISSUE TITLE
[BUG] GitHub comment not appearing

### ISSUE THREAD

**Issue by kasvith** [FirebaseExtended/action-hosting-deploy#294]
### Action config

```yaml
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: preview
          projectId: appname
```

### Error message

No Errors

### Expected behavior

GithHub comment to be appear in PR

### Actual behavior

No comments appearing in PR. But we get the deploy URL in the deploy log
