### ISSUE TITLE
[BUG] stream-json parse error

### ISSUE THREAD

**Issue by Goldziher** [FirebaseExtended/action-hosting-deploy#323]
### Action config

```
            - uses: FirebaseExtended/action-hosting-deploy@v0
              if: ${{ inputs.is_preview == false }}
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
                  projectId: '${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}'
                  channelId: live
```

### Error message

```shell
Error: Parser has expected a string value
      at Parser._processBuffer (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/stream-json/Parser.js:205:45)
      at Parser._flush (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/stream-json/utils/Utf8Stream.js:49:10)
      at Parser._flush (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/stream-json/Parser.js:83:11)
      at Parser.final [as _final] (node:internal/streams/transform:132:10)
      at callFinal (node:internal/streams/writable:698:12)
      at prefinish (node:internal/streams/writable:710:7)
      at finishMaybe (node:internal/streams/writable:720:5)
      at Writable.end (node:internal/streams/writable:634:5)
      at Socket.onend (node:internal/streams/readable:716:10)
      at Object.onceWrapper (node:events:631:28)
```

### Expected behavior

No parsing error.

### Actual behavior

The `stream-json` library's parser is throwing an exception.

It might be related to this issue in the `stream-json` repo: https://github.com/uhop/stream-json/issues/87
