### ISSUE TITLE
[BUG] preview hosts are not being added to the authorized domains list

### ISSUE THREAD

**Issue by rosostolato** [FirebaseExtended/action-hosting-deploy#347]
I always used this action to deploy preview links for my PRs. But, recently, the google authenticator stopped working for my app because the preview domain isn't being added to the "authorized domains" list anymore.

I don't know if this is Firebase or this action plugin fault.

### Action config

```
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    expires: 30d
    projectId: my-awesome-project
```

### Error message

No errors. It deploys successfully.

### Expected behavior

Expected to have the new preview URL domain added to the firebase authorized domains.

### Actual behavior

The preview link is created, posted to the PR comments but the domain is not added to the authorized domains, causing google auth to not work on the preview link.
