### ISSUE TITLE
[BUG] Unexpected token r in JSON at position 2

### ISSUE THREAD

**Issue by nvzoll** [FirebaseExtended/action-hosting-deploy#359]
### Action config

```
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                  export NODE_OPTIONS=--max_old_space_size=4096
                  npm ci && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
                  channelId: live
                  projectId: ...
                  target: ...
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
                  NODE_OPTIONS: "--max_old_space_size=4096"
```

### Error message

Github action log

```
Run FirebaseExtended/action-hosting-deploy@v0
Verifying firebase.json exists
Setting up CLI credentials
Deploying to production site
  /usr/local/bin/npx firebase-tools@latest deploy --only hosting:...--project ... --json
  npm WARN exec The following package was not found and will be installed: firebase-tools@13.6.0
  No Firebase app associated with site ..., injecting project default config.
    You can link a Web app to a Hosting site here https://console.firebase.google.com/project/.../settings/general/web
  info  - Loaded env from /home/runner/work/.../.env
  info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
  info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
  info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
  npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
  npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  npm WARN deprecated vm2@3.9.[19](https://github.com/.../actions/runs/.../job/...#step:4:22): The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
  
  added 1405 packages in 26s
  
  181 packages are looking for funding
    run `npm fund` for details
  Error: Unexpected token r in JSON at position 2
  ***
    conclusion: 'failure',
    output: ***
      title: 'Deploy preview failed',
      summary: 'Error: Unexpected token r in JSON at position 2'
    ***
  ***
```
### Expected behavior

Workflow run ends successfully

### Actual behavior

Workflow run fails, but usually successfully deploys after manual restart.
