### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by danhenderson95** [FirebaseExtended/action-hosting-deploy#38]
I'm getting the following error when I use this action: "Error: Unexpected token  in JSON at position 0".

The step in my workflow that produces this error does actually deploy both sites correctly, but seems to error on the success message that is returned in the "Deploying to production site" step.

**The below are logs of the action.**

Run FirebaseExtended/action-hosting-deploy@v0
Verifying firebase.json exists
Setting up CLI credentials
Deploying to production site
  /usr/local/bin/npx firebase-tools deploy --only hosting --project MY_PROJECT_ID --json
  ***
    "status": "success",
    "result": ***
      "hosting": [
        "sites/MY_SITE_A/versions/VERSION_A",
        "sites/MY_SITE_B/versions/VERSION_B"
      ]
    ***
  ***
  Error: Unexpected token  in JSON at position 0

**Comment by bartholomej** [comment]
I think there is a problem with multiple targets or Firebase multi domains settings.

I tried to create example repository for everyone, but I'm having the same issue
[bartholomej/firebase-preview-channels-example](https://github.com/bartholomej/firebase-preview-channels-example)

### This configuration does **NOT** work ❌
**Pull request**: https://github.com/bartholomej/firebase-preview-channels-example/pull/2
**Firebaserc**: https://github.com/bartholomej/firebase-preview-channels-example/blob/universal/.firebaserc
**Github action log**: https://github.com/bartholomej/firebase-preview-channels-example/runs/1238885320?check_suite_focus=true

I am getting the following error: ```(Error: Unexpected token  in JSON at position 0)```
But channel was actually deployed: https://mypreviewchannels--pr2-universal-dw435npv.web.app/

### This configuration works perfectly ✅
**Pull request**: https://github.com/bartholomej/firebase-preview-channels-example/pull/1
**Firebaserc**: https://github.com/bartholomej/firebase-preview-channels-example/blob/github-link/.firebaserc
**Github action log**: https://github.com/bartholomej/firebase-preview-channels-example/runs/1238673033?check_suite_focus=true 

### Workaround

This is my workaround for pull requests flow

```yaml
- name: Extract branch name
  shell: bash
  run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

- name: Deploy Firebase Preview Channel
  run: yarn firebase hosting:channel:deploy ${{ env.BRANCH_NAME }} --project project-name --token ${{ secrets.FIREBASE_TOKEN }}
```
Thank you for your great work: @jhuleatt and everyone ;)

**Comment by Eronne** [comment]
I am using multiple targets and I am facing the same issue

**Comment by mbleigh** [comment]
Can you check to make sure you're not targeting `@v0` (which is what the Firebase CLI sets up by default)? I had the issue but changing the YAML to target `@0.3-alpha` fixed it.

**Comment by bartholomej** [comment]
@mbleigh I confirm. Version `@v0.3-alpha` resolves the issue 🎉 Thanks

``` yaml
- uses: FirebaseExtended/action-hosting-deploy@v0.3-alpha
  with:
    repoToken: '${{ secrets.GITHUB_TOKEN }}'
    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYPREVIEWCHANNELS }}'
    projectId: mypreviewchannels
  env:
    FIREBASE_CLI_PREVIEWS: hostingchannels
```

**Github Actions log:** 
https://github.com/bartholomej/firebase-preview-channels-example/runs/1249563075?check_suite_focus=true
