### ISSUE TITLE
Allow Passing of Build Parameters

### ISSUE THREAD

**Issue by ChrisDeardeuff** [FirebaseExtended/action-hosting-deploy#387]
### The use case you're trying to solve

To my understanding from reading about similar problems, the project is rebuilt when firebase deploy is ran. This overrides any files that have been built before and thus ignores variables passed with --dart-define.

It would be nice to be able to specify '--dart-define var=value' parameters for building. 

### Change to the action that would solve that use case

Allow them to be passed in the ENV section of the yml. Example:
```yml
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets }}
          firebaseServiceAccount: ${{ secrets}}
          channelId: <channelid>
          projectId: <projectId>
        env:
         FIREBASE_CLI_EXPERIMENTS: webframeworks
         ADDITIONAL_BUILD_ARGS: --dart-define var=value --dart-define var2=value2
```

### Other considerations
Possibly instead have a flag that stops the build process during deploy?
