### ISSUE TITLE
[BUG] Failed to parse private key: Error: Only 8, 16, 24, or 32 bits supported: 528

### ISSUE THREAD

**Issue by rosostolato** [FirebaseExtended/action-hosting-deploy#396]
I just used `firebase init hosting:github` to initialize the github action as I always do but after it compiles the code it gives this error.

### Error message

```
FirebaseAppError: Failed to parse private key: Error: Only 8, 16, 24, or 32 bits supported: 528
```

### Action config

```
  - uses: FirebaseExtended/action-hosting-deploy@v0
    with:
      repoToken: ${{ secrets.GITHUB_TOKEN }}
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LANGUAGE_LIT }}
      channelId: live
      projectId: language-lit
```
