### ISSUE TITLE
[BUG] channelId can't be blank

### ISSUE THREAD

**Issue by wneel** [FirebaseExtended/action-hosting-deploy#403]
### Action config

**Env:**
node: v18.20.5
npm: 10.8.2
firebase-tools: 13.29.1

```yml
uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_XXX }}
          projectId: xxx
          firebaseToolsVersion: "13.29.1"
          channelId:
          # same issue with "channelId" blank or without
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FIREBASE_FRAMEWORKS_BUILD_TARGET: production
```
### Error message

```json
[command]/opt/hostedtoolcache/node/18.20.5/x64/bin/npx firebase-tools@13.29.1 hosting:channel:deploy  --expires 7d --project xxx --json
{
  "status": "error",
  "error": "channelID is currently required"
}{
  "status": "error",
  "error": "channelID is currently required"
}
The process '/opt/hostedtoolcache/node/18.20.5/x64/bin/npx' failed with exit code 1
```

### Expected behavior

According to the [README](https://github.com/FirebaseExtended/action-hosting-deploy?tab=readme-ov-file#channelid-string) the `channelId` can be manually set to `live` or leaved blank or "will be auto-generated per branch or PR".

When leaved blank no error should occur.

### Actual behavior

Currently, in my case no channelID is generated and [this line](https://github.com/firebase/firebase-tools/blob/774d3f0580c8fa91c8e95378f79f28e60e1b867d/src/commands/hosting-channel-deploy.ts#L74) is being triggerd.
