### ISSUE TITLE
502 error on preview deployment.

### ISSUE THREAD

**Issue by mather** [FirebaseExtended/action-hosting-deploy#45]
In my branch `feature/event-input-form`, deployment to hosting preview channel always failed with 502 error.

```
  /opt/hostedtoolcache/node/14.13.1/x64/bin/npx firebase-tools hosting:channel:deploy pr22-feature_event-input- --expires 10d --project ??? --json
  ***
    "status": "error",
    "error": "HTTP Error: 502, Unknown Error"
  ***
  ***
    "status": "error",
    "error": "HTTP Error: 502, Unknown Error"
  ***
```

But in another branch named `feature/event-input`, deployed successfully.

I think CHANNEL_ID ( `pr22-feature_event-input-` ) which end with `-` cause the error.

In this code, clipped branch name might have `-` at end of string.

https://github.com/FirebaseExtended/action-hosting-deploy/blob/79d1e17528573ce1a02632923c928f62009df3c3/src/getChannelId.ts#L25

Anyone know such rules about CHANNEL_ID?

ref: https://firebase.google.com/docs/hosting/manage-hosting-resources

**Comment by mather** [comment]
With local firebase-tools, this command reproduce the same error.

```
$ firebase hosting:channel:deploy event-input-

Error: HTTP Error: 502, Unknown Error
```

**Comment by jhuleatt** [comment]
Thank you for reporting, @mather! Since this is an issue with the CLI itself, I've filed a bug in the firebase-tools repo: https://github.com/firebase/firebase-tools/issues/2724

**Comment by jhuleatt** [comment]
Got hit by this in a PR on this repo: https://github.com/FirebaseExtended/action-hosting-deploy/pull/47/checks?check_run_id=1288918196

**Comment by mather** [comment]
Workaround: set `channelId` option.
https://github.com/FirebaseExtended/action-hosting-deploy#channelid-string

**Comment by WiNloSt** [comment]
I use `channelId` as @mather commented. It worked really well. Also, in case someone wants to still use a similar channel ID like this action produces. I set my action file like this.

I remove the trailing `_` or `-` that would cause the deployment to fail.
```yaml
      - id: set-firebase-hosting-channel-id
        name: set Firebase preview channel projectId
        run: echo "::set-output name=channel-id::$(echo pr${{ github.event.number }}-$(echo ${{ github.event.pull_request.head.ref }} | cut -c1-20) | sed -e 's/[-_]$//g' | sed -e 's/[^a-zA-Z0-9\.\-]/_/g')"

      # then you can use the channelId like so
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: ${{ steps.set-firebase-hosting-channel-id.outputs.channel-id }}
```
