### ISSUE TITLE
Support firebase.json that isn't in the root of the repo

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/action-hosting-deploy#5]
For cases where the `firebase.json` file isn't at the root of the repo, we should allow configuration of the path to point to a specific spot.

For example:

```yml
- uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    projectId: my-project
    path: "./website" # Action will cd into this path before running
```
