### ISSUE TITLE
[BUG] Github Action deploy when install a new package

### ISSUE THREAD

**Issue by stevecode21** [FirebaseExtended/action-hosting-deploy#82]
### Action config

```
name: Deploy to Firebase Hosting on merge into the staging environment
'on':
  push:
    branches:
      - staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build:staging
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAASMARKETINGFORMULA }}'
          channelId: live
          projectId: xxxxxx
          target: xxxxx
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

```

### Error message

I'm getting this error when **I install a new package** and then push it to deploy by GitHub action
_The error just reproduces when I install a new package_
![image](https://user-images.githubusercontent.com/59179297/108257925-7a0be900-712d-11eb-8a5b-a68051c441a7.png)

### Expected behavior

Deploy successful

### Actual behavior

Error when trying to deploy to Firebase Hosting
