### ISSUE TITLE
Channel ID from Commit

### ISSUE THREAD

**Issue by TheKingOfAtlantis** [FirebaseExtended/action-hosting-deploy#90]
Currently have it setup that PR onto the dev or main branch trigger deployment of a preview, but would be great if a preview deployment could be triggered on a merge - Currently no channel id gets generated in this case resulting in an error and a failed action because no channel id is supplied

The sha or subject of the commit on a push could be used to generate the channel Id instead, allowing for this use case

**Comment by othondev** [comment]
is there workaround?

**Comment by sampi** [comment]
my workaround was to manually specify the `channelId`, based on the current code: https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/bin/action.min.js#L11267

```yaml
- name: Deploy to Firebase (preview)
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: '${{ secrets.GITHUB_TOKEN }}'
    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
    expires: 3d
    projectId: my-project-id
    channelId: 'pr${{ github.context.payload.pull_request.number }}-${{ github.context.payload.pull_request.head.ref }}'
```
