### ISSUE TITLE
  Error: channelID is currently required

### ISSUE THREAD

**Issue by lukepighetti** [FirebaseExtended/action-hosting-deploy#98]
Our hosting preview deploys randomly quit working last night. We have no changes on our end. Now it fails saying `channelID is currently required.` Haven't been able to find anything in the changelogs. Is there somewhere else I should be looking?

### Action config

```
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEADFERNO }}"
          projectId: leadferno
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

### Error message

```
Error: channelID is currently required
```

### Expected behavior

It deploys

### Actual behavior

It doesn't
