### ISSUE TITLE
Deploy to multiple environments

### ISSUE THREAD

**Issue by lukepighetti** [FirebaseExtended/action-hosting-deploy#99]
Let's say we want to deploy a preview of one commit to two environments. In our build step we will provide different API base urls for each envirnoment, `dev` and `qa`.

Is there any way to achieve this?

I suspect we can do two deploy steps, but it's not clear how we display in each message which environment the link is for.

**Comment by lukepighetti** [comment]
Perhaps we could wildcard the random channelid? So we could say

### DEV environment
```
...
      - run: flutter build web --web-renderer canvaskit --release --dart-define=LF_API=https://api-dev.leadferno.com/v0/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEADFERNO }}"
          projectId: foo
          channelId: *-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

### QA environment

```
...
      - run: flutter build web --web-renderer canvaskit --release --dart-define=LF_API=https://api-qa.leadferno.com/v0/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEADFERNO }}"
          projectId: foo
          channelId: *-qa
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

With the expectation that two build messages would come in, with two links, one for `dev` and the other `qa`

**Comment by lukepighetti** [comment]
Perhaps we could wildcard the random channelid? So we could say

### DEV environment
```
...
      - run: flutter build web --web-renderer canvaskit --release --dart-define=API=https://api-dev.foo.com/v0/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOO }}"
          projectId: foo
          channelId: *-dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

### QA environment

```
...
      - run: flutter build web --web-renderer canvaskit --release --dart-define=LF_API=https://api-qa.foo.com/v0/
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: foo
          channelId: *-qa
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

With the expectation that two build messages would come in, with two links, one for `dev` and the other `qa`
